const REGEX = 'regex';
const DEFAULTVALUESET = [{
    value: 'True',
    displayValue: 'Yes',
    lang: 'en'
}, {
    value: 'False',
    displayValue: 'No',
    lang: 'en'
}];

const AUTOGENERATEDFIELDS = { 'site': ['siteID'], 'tncdetails': ['tncNumber'] };

module.exports = { REGEX, DEFAULTVALUESET, AUTOGENERATEDFIELDS };
