export default {
    MANAGESUPPLIER: 'Manage a Supplier - th',
    CREATESUPPLIER: 'Create a new supplier - th',
    SUPPLIER: 'Supplier',
    SITE: 'Site',
    PAYMENT_TERMS: 'Payment Terms',
    CREATE_NEW_SUPPLIER_TEXT: 'Create a new supplier - th',
    CREATE_NEW_SUPPLIER_SUBTEXT:
        'We will tell you if there are any matching records',
    CONFIRM_BTN: 'Confirm Supplier Details - th',
    SUCCESS_INFO: 'Supplier record successfully saved',
    VALIDATION_ERROR:
        'Form has errors. Please check the highlighted fields and fill the information properly',
    authCookie: 'OAuth.AccessToken.EP',
    heading: 'Find a Supplier',
    subHeading: 'Please enter any one of the fields',
    supplierNameText: 'Search for supplier name',
    supplierNumberText: 'Search for supplier reference number',
    supplierNamePlaceHolder: 'Enter supplier name..',
    supplierNumberPlaceHolder: 'Enter supplier number..',
    searchButton: 'Find supplier',
    inputValid: 'Please enter atleast one field',
    supplierNameError: 'Please enter a Supplier name',
    supplierNumberError: 'Please enter a Supplier number',
    supplierNotFound: 'No partner found',
    invalidSupplierName: 'Please enter valid Partner name',
    invalidSupplierNumber: 'Please enter valid Supplier number',
    addNew: 'addNew',
    searchListHeading: 'Matches found for supplier',
    select: 'Select',
    createNew: 'Create New',
    create: 'Create',
    editDetails: 'Edit details',
    supplierName: 'Supplier name',
    companiesHouseName: 'Companies House name',
    companyRegistrationNumber: 'Company registration number',
    vatNumber: 'VAT number',
    tableHead: 'Multiple matches found. Select an existing site to view its details, or create a new site for this supplier.',
    associatedWithSupplier: 'Associated with supplier',
    CONTACT_ADMIN_FOR_ACCESS: 'Sorry, does not have sufficent access, Please contact admin.',
    SITE_TABLE_HEAD: [null, 'Site Name', 'Site Id'],
    SITE_BODY_VALUES: ['siteName', 'siteCodeId'],
    PAYMENT_BODY_VALUES: ['paymentTermsName'],
    PAYMENT_TABLE_HEAD: [null, 'TNC number'],
    SELECT: 'Select',
    ADD_NEW: 'Add new',
    supplierDetails: 'supplier details',
    stepTwoSubTitle: 'Further explination text to aid understanding of current mode and functions available',
    siteDetails: 'Site details',
    globalErrorMessage: {
        403: {
          title: `We're sorry, unauthorized access.`,
          body: 'Unfortunately a 403 error occured',
        },
        404: {
          title: 'We’re sorry we couldn’t find the page you were looking for.',
          body: 'Unfortunately a 404 error occured',
        },
      },
   attributeGroupType: 'Case', 
   id: 'Id',
  view: 'View',
  cancelFormText: 'Are you sure you want to cancel? You will lose any unsaved data.',
  save: 'Save',
  cancel: 'Cancel',
  yesCancel: 'Yes, cancel',
  no: 'No'
};
